version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
        db:
          condition: service_healthy
    environment:
      SPRING DATASOURCE URL: jdbc:postgresql://db:5432//demodb
      SPRING DATASOURCE USERNAME: postgres
      SPRING DATASOURCE PASSWORD: password


