name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Build demo-app docker image
      run: docker build . --file Dockerfile --tag demo-app:latest
    - name: Pull postgres:15-alpine docker image
      run: docker pull postgres:15-alpine
      
    - name: Install Snyk
      run: |
          npm install -g snyk

    - name: Test Docker Image for Vulnerabilities
      run: snyk test --docker demo-app:latest

